from typing import Dict, Type

from absl import logging

from python.game.events.battle_event import (
    AbilityEvent,
    ActivateEvent,
    BattleEndEvent,
    BattleEvent,
    BattleStartEvent,
    BoostEvent,
    CantEvent,
    ClearAllBoostEvent,
    ClearBoostEvent,
    ClearNegativeBoostEvent,
    ClearPokeEvent,
    CritEvent,
    CureStatusEvent,
    DamageEvent,
    DetailsChangeEvent,
    DragEvent,
    EndAbilityEvent,
    EndItemEvent,
    EndVolatileEvent,
    FailEvent,
    FaintEvent,
    FieldEndEvent,
    FieldStartEvent,
    FormeChangeEvent,
    GameTypeEvent,
    GenEvent,
    HealEvent,
    HitCountEvent,
    ImmuneEvent,
    ItemEvent,
    MissEvent,
    MoveEvent,
    PlayerEvent,
    PokeEvent,
    PrepareEvent,
    PrivateMessageEvent,
    ReplaceEvent,
    RequestEvent,
    ResistedEvent,
    SetBoostEvent,
    SetHpEvent,
    SideEndEvent,
    SideStartEvent,
    SingleMoveEvent,
    SingleTurnEvent,
    StartVolatileEvent,
    StatusEvent,
    SuperEffectiveEvent,
    SwitchEvent,
    TeamPreviewEvent,
    TeamSizeEvent,
    TerastallizeEvent,
    TierEvent,
    TransformEvent,
    TurnEvent,
    UnboostEvent,
    UnknownEvent,
    UpkeepEvent,
    WeatherEvent,
)


class MessageParser:
    MESSAGE_TYPE_MAP: Dict[str, Type[BattleEvent]] = {
        "turn": TurnEvent,
        "start": BattleStartEvent,
        "win": BattleEndEvent,
        "player": PlayerEvent,
        "teamsize": TeamSizeEvent,
        "gen": GenEvent,
        "tier": TierEvent,
        "gametype": GameTypeEvent,
        "pm": PrivateMessageEvent,
        "switch": SwitchEvent,
        "drag": DragEvent,
        "-damage": DamageEvent,
        "-heal": HealEvent,
        "faint": FaintEvent,
        "-status": StatusEvent,
        "-curestatus": CureStatusEvent,
        "move": MoveEvent,
        "-boost": BoostEvent,
        "-unboost": UnboostEvent,
        "-setboost": SetBoostEvent,
        "-clearboost": ClearBoostEvent,
        "-clearallboost": ClearAllBoostEvent,
        "-clearnegativeboost": ClearNegativeBoostEvent,
        "-ability": AbilityEvent,
        "-endability": EndAbilityEvent,
        "-item": ItemEvent,
        "-enditem": EndItemEvent,
        "-start": StartVolatileEvent,
        "-end": EndVolatileEvent,
        "-singleturn": SingleTurnEvent,
        "-singlemove": SingleMoveEvent,
        "-weather": WeatherEvent,
        "-fieldstart": FieldStartEvent,
        "-fieldend": FieldEndEvent,
        "-sidestart": SideStartEvent,
        "-sideend": SideEndEvent,
        "-terastallize": TerastallizeEvent,
        "-formechange": FormeChangeEvent,
        "-transform": TransformEvent,
        "-activate": ActivateEvent,
        "-prepare": PrepareEvent,
        "cant": CantEvent,
        "-supereffective": SuperEffectiveEvent,
        "-resisted": ResistedEvent,
        "-immune": ImmuneEvent,
        "-crit": CritEvent,
        "-miss": MissEvent,
        "-fail": FailEvent,
        "-hitcount": HitCountEvent,
        "-sethp": SetHpEvent,
        "replace": ReplaceEvent,
        "detailschange": DetailsChangeEvent,
        "poke": PokeEvent,
        "clearpoke": ClearPokeEvent,
        "teampreview": TeamPreviewEvent,
        "upkeep": UpkeepEvent,
        "request": RequestEvent,
    }

    def parse(self, raw_message: str) -> BattleEvent:
        parts = raw_message.split("|")
        message_type = parts[1] if len(parts) > 1 else ""

        event_class = self.MESSAGE_TYPE_MAP.get(message_type)
        if event_class:
            return event_class.parse_raw_message(raw_message)

        logging.warning("Unknown message type: %s", message_type)
        return UnknownEvent(raw_message=raw_message, message_type=message_type)
